config/routes.rb
Rails.application.routes.draw do
    devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new', as: "new_user_registration"
    delete 'logout', to: 'devise/sessions#destroy'
  end

  # Below for all other routes:
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :products do
    resources :comments
  end
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  root 'static_pages#landing_page'

  post 'static_pages/thank_you'
  post 'payments/create'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bro Reps</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Ribeye" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="page-container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand">
              <%= link_to(image_tag("Logo.png", id: "logo"), root_path) %>
            </a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Products", products_path %></li>
              <li><%= link_to "About", static_pages_about_path %></li>
              <li><%= link_to "Contact", static_pages_contact_path %></li>
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown">Account
                  <span class="caret"></span></a>    
                  <ul class="dropdown-menu">
                    <li>            
                      <%= link_to('Log Out', logout_path, :method => :delete) %>
                    </li>
                    <li>
                      <%= link_to('Edit Profile', edit_user_registration_path) %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li>
                  <%= link_to('Log In', login_path) %>
                </li>
              <% end %>
              <li>
                <div class="form-group-sm">
                    <%= form_tag("/products", method: "get", id: "search") do %>
                      <%= text_field_tag(:q, nil,  class: "form-control search-box", placeholder: "Search...") %>
                      <%= button_tag(type: "submit", class: "btn btn-primary search-button") do %>
                          <span class="glyphicon glyphicon-search"></span>
                      <% end %>
                    <% end %>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <% if notice %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% elsif alert %>
        <div class="alert alert-warning">
          <%= alert %>
        </div>
      <% end %>
      
      <div class="content">
        <%= yield %>
      </div>
      <footer>
        <hr>
        <div class="container-fluid">
          <p>&copy; 2017 Bro Reps, Inc.</p>
          <p class="right">CrossFit® is the registered trademark of CrossFit, Inc.</p>
        </div>
      </footer>
    </div> <!--end page container -->
  </body>
</html>